### PR TITLE
fix numbering in README

### PR DESCRIPTION
**Pull request by bermarte**
---
name: code review PR
about: A template PR for contributing to this project
---

## Checklists

- [x] All CI checks pass
- [x] the branch is up to date with `main`/`master`
- [x] the code works when pulled and run locally

## Markdown

- [x] the markdown source is formatted
- [x] spelling and grammar is correct in all text
- [x] The markdown looks correct when you preview the file
- [x] all links and images work

### CODE REVIEW

**Comment by bermarte** [comment]
I can't add reviewers

**Review by samirm00 — APPROVED** [review]
I can't merge it too.

**Comment by samirm00** [comment]
@bermarte , I think the repo is not ours, that is why?

**Comment by bermarte** [comment]
> I can't merge it too. I am not an admin on this repo

I think [Daniel](https://github.com/danielhalasz) has full access

**Pull request merged**
